services:
  solodesign-app:
    image: ${IMAGE_OVERRIDE:-solodesign:latest}
    container_name: solodesign-frontend
    ports:
      - "3010:3000"
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
      LOG_TO_FILE: "true"
      LOG_LEVEL: "info"
    volumes:
      # PERSISTENCE CRITIQUE: Données et uploads
      - ./data:/app/data:rw
      - ./data/uploads:/app/public/uploads:rw
      # Logs pour monitoring
      - ./logs:/app/logs:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://127.0.0.1:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - npm_network
    # Améliorer les performances I/O pour éviter EBUSY
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

networks:
  npm_network:
    external: true
