services:
  solodesign-app:
    image: ${IMAGE_OVERRIDE:-solodesign:latest}
    container_name: solodesign-frontend
    ports:
      - "3010:3000"
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
      LOG_TO_FILE: "true"
      LOG_LEVEL: "info"
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://127.0.0.1:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - npm_network

networks:
  npm_network:
    external: true
